[2016-03-15 11:19:58] [New I/O boss #9] [ERROR] [asynhttp.AsynHttpUitl$1] [33] - doAsynHttpGet catch exception-->http://localhost:9696/testServlet
